### ISSUE TITLE
Failure: twisted.internet.error.ConnectionRefusedError

### ISSUE THREAD

**Issue by jfnz** [dashpay/p2pool-dash#29]
Having trouble running p2pool-dash

```
user@srv01:~/p2pool-dash$ python run_p2pool.py <username> <password>
2017-05-20 05:53:08.752461 p2pool (version 5fd602d)
2017-05-20 05:53:08.753194
2017-05-20 05:53:08.753351 Testing dashd RPC connection to 'http://127.0.0.1:9998/' with username '<username>'...
Error while checking dash connection:
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

Config file is:

```
server=1
daemon=1
rpcpassword=<password>
rpcuser=<user>
rpcport=7903
port=9998
rpcallowip=127.0.0.1
```

What's wrong here?

**Comment by ourlink** [comment]
The port number is incorrect. I know the documentation says 9998 but the actual port is 8999.
Switch your port setting to 8999 and it should work fine for you.

**Comment by chaeplin** [comment]
dashd side 
https://github.com/dashpay/p2pool-dash/blob/e8d4618cb66a370e560f276a78642db1d0772f6d/p2pool/dash/networks/dash.py#L11-L14

```
P2P_PORT = 9999
RPC_PORT = 9998
```

p2pool side
https://github.com/dashpay/p2pool-dash/blob/e8d4618cb66a370e560f276a78642db1d0772f6d/p2pool/networks/dash.py
```
P2P_PORT = 8999
WORKER_PORT = 7903
```

change your dash.conf 
```
rpcport= 9998
port= 9999 
```

**Comment by wojtas85** [comment]
Any chance we can stop people from accessing the node through a vpn? lol. Cut them off and let me get some extra cash for like a month, lol hmm?

**Comment by Mentors4EDU** [comment]
Were you ever able to fully fix the python twister connection error?

**Comment by iqbal502** [comment]
Hello All,

I am also getting similar type of error (refer below) any idea anyone what could be the exact issue ?


Traceback (most recent call last):
  File "/opt/wab/bin/WABSendDelayedNotifications", line 29, in <module>
    send_delayed_notifications_script(*sys.argv[1:])
  File "/opt/wab/lib/python2.7/site-packages/wabchgpwd/cron.py", line 145, in send_delayed_notifications_script
  File "/opt/wab/lib/python2.7/site-packages/wabchgpwd/cron.py", line 75, in __init__
  File "/opt/wab/lib/python2.7/site-packages/wabchgpwd/cron.py", line 42, in get_proxy
  File "/opt/wab/lib/python2.7/site-packages/wabengine/client/common.py", line 185, in authenticate_as_operator
  File "/opt/wab/lib/python2.7/site-packages/wabengine/client/common.py", line 241, in _do_login
  File "/opt/wab/lib/python2.7/site-packages/wabengine/client/common.py", line 38, in _call
  File "/usr/lib/python2.7/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "<string>", line 2, in raiseException
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
