### ISSUE TITLE
centos help

### ISSUE THREAD

**Issue by 200787128** [dashpay/p2pool-dash#32]
centos7 install dashd  need run? lparam is?  

python run_p2pool.py

Testing dashd RPC connection to 'http://127.0.0.1:9998/' with username ''...
2017-09-28 21:46:18.163593 > Error while checking Dash connection:

/root/.dash/dash.conf ???

**Comment by 200787128** [comment]
tcp        0      0 127.0.0.1:9998          0.0.0.0:*               LISTEN      30389/dashd         
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      30389/dashd         
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      29561/nginx: master 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      3061/sshd           
tcp        0      0 127.0.0.1:88            0.0.0.0:*               LISTEN      30123/httpd         
tcp6       0      0 :::3306                 :::*                    LISTEN      30090/mysqld        
tcp6       0      0 :::9999                 :::*                    LISTEN      30389/dashd

**Comment by 200787128** [comment]
Testing dashd RPC connection to 'http://127.0.0.1:9998/' with username 'kekai'...
2017-09-29 20:48:24.577842 > Error while checking dash connection:
2017-09-29 20:48:24.577916 > Traceback (most recent call last):
2017-09-29 20:48:24.577936 >   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
2017-09-29 20:48:24.577954 >     current.result = callback(current.result, *args, **kw)
2017-09-29 20:48:24.577971 >   File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1101, in gotResult
2017-09-29 20:48:24.577988 >     _inlineCallbacks(r, g, deferred)

**Comment by 200787128** [comment]
root/.dashcore/dash.conf 
server=1
daemon=1
rpcpassword=testkekai
rpcuser=kekai

**Comment by 200787128** [comment]
p2pool.util.jsonrpc.NarrowError: -10 Dash Core is syncing with network...   ？？？
