### ISSUE TITLE
Error in DeferredResource handler - will not boot

### ISSUE THREAD

**Issue by buechling** [dashpay/p2pool-dash#4]
So will P2pool still work with actual darkcoin version?
i can not bootstrap..

```
2015-02-01 17:19:23.335160 p2pool (version f143646-dirty)
2015-02-01 17:19:23.335205
2015-02-01 17:19:23.335237 Testing bitcoind RPC connection to 'http://127.0.0.1:9998/' with username '**'...
2015-02-01 17:19:23.349570     ...success!
2015-02-01 17:19:23.349632     Current block hash: 11eb275dcf226bd241357d4f88576fe1bd1fbf8f6a8eb010e02d80
2015-02-01 17:19:23.349669     Current block height: 212949
2015-02-01 17:19:23.349701
2015-02-01 17:19:23.349734 Testing bitcoind P2P connection to '127.0.0.1:9999'...
2015-02-01 17:19:23.386891     ...success!
2015-02-01 17:19:23.386942
2015-02-01 17:19:23.386973 Determining payout address...
2015-02-01 17:19:23.387055     ...success! Payout address: ***
2015-02-01 17:19:23.387079
2015-02-01 17:19:23.387095 Loading shares...
2015-02-01 17:19:23.387179     ...done loading 0 shares (0 verified)!
2015-02-01 17:19:23.387209
2015-02-01 17:19:23.387226 Initializing work...
2015-02-01 17:19:23.541975     ...success!
2015-02-01 17:19:23.542088
2015-02-01 17:19:23.542144 Joining p2pool network using port 8999...
2015-02-01 17:19:23.733680 > Unhandled Error
2015-02-01 17:19:23.733777 > Traceback (most recent call last):
2015-02-01 17:19:23.733814 > Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'asia01.poolhash.org' not found: [Errno -2] Name or service not known.
2015-02-01 17:19:23.733939 > Unhandled Error
2015-02-01 17:19:23.733982 > Traceback (most recent call last):
2015-02-01 17:19:23.734011 > Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'asia02.poolhash.org' not found: [Errno -2] Name or service not known.
2015-02-01 17:19:23.734184 > Unhandled Error
2015-02-01 17:19:23.734226 > Traceback (most recent call last):
2015-02-01 17:19:23.734254 > Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'cryptohasher.net' not found: [Errno -2] Name or service not known.
2015-02-01 17:19:23.911223     ...success!
2015-02-01 17:19:23.911328
2015-02-01 17:19:23.911636 Listening for workers on '' port 7903...
2015-02-01 17:19:23.937680     ...success!
2015-02-01 17:19:23.937717
2015-02-01 17:19:23.937732 Started successfully!
2015-02-01 17:19:23.937746 Go to http://127.0.0.1:7903/ to view graphs and statistics!
2015-02-01 17:19:23.937764 Donating 0.1% of work towards P2Pool's development. Please donate to encourage further development of P2Pool!
2015-02-01 17:19:23.937776
2015-02-01 17:19:26.939465 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2015-02-01 17:19:26.939521  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2015-02-01 17:19:30.854181 > Error in DeferredResource handler:
2015-02-01 17:19:30.854232 > Traceback (most recent call last):
2015-02-01 17:19:30.854250 >   File "/home/p2pool/p2pool-drk/p2pool/util/deferred_resource.py", line 24, in render
2015-02-01 17:19:30.854262 >     defer.maybeDeferred(resource.Resource.render, self, request).addCallbacks(finish, finish_error)
2015-02-01 17:19:30.854275 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
2015-02-01 17:19:30.854286 >     result = f(*args, **kw)
2015-02-01 17:19:30.854297 >   File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
2015-02-01 17:19:30.854307 >     return m(request)
2015-02-01 17:19:30.854317 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
2015-02-01 17:19:30.854327 >     return _inlineCallbacks(None, gen, Deferred())
2015-02-01 17:19:30.854337 > --- <exception caught here> ---
2015-02-01 17:19:30.854346 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
2015-02-01 17:19:30.854355 >     result = g.send(result)
2015-02-01 17:19:30.854365 >   File "/home/p2pool/p2pool-drk/p2pool/web.py", line 197, in render_GET
2015-02-01 17:19:30.854374 >     res = yield self.func(*self.args)
2015-02-01 17:19:30.854383 >   File "/home/p2pool/p2pool-drk/p2pool/web.py", line 202, in <lambda>
2015-02-01 17:19:30.854394 >     web_root.putChild('rate', WebInterface(lambda: p2pool_data.get_pool_attempts_per_second(node.tracker, node.best_share_var.value, decent_height())/(1-p2pool_data.get_average_stale_prop(node.tracker, node.best_share_var.value, decent_height()))))
2015-02-01 17:19:30.854406 >   File "/home/p2pool/p2pool-drk/p2pool/data.py", line 573, in get_pool_attempts_per_second
2015-02-01 17:19:30.854415 >     assert dist >= 2
2015-02-01 17:19:30.854424 > exceptions.AssertionError:
2015-02-01 17:19:37.302591 Handshake timed out, disconnecting from 94.242.222.27:8999
2015-02-01 17:19:37.639532 Handshake timed out, disconnecting from 104.207.128.111:8999
2015-02-01 17:19:41.940011 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2015-02-01 17:19:41.940103  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2015-02-01 17:19:51.851860 Handshake timed out, disconnecting from 192.241.246.214:8999
2015-02-01 17:19:56.941300 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2015-02-01 17:19:56.941425  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2015-02-01 17:19:57.349997 Handshake timed out, disconnecting from 104.207.128.111:8999
2015-02-01 17:19:58.100211 Handshake timed out, disconnecting from 92.222.1.173:8999
2015-02-01 17:19:58.353573 Handshake timed out, disconnecting from 94.242.222.27:8999
```

**Comment by UdjinM6** [comment]
outdated, closing..
