### ISSUE TITLE
Couldn't link returned work's job id with its handler.

### ISSUE THREAD

**Issue by Rem559** [dashpay/p2pool-dash#59]
The error manifested itself when the traffic came to the pool 2.34th, before that on this pool works my own asics attached to the local network. In addition to p2p dash, mue p2pool and open ethreum (nodejs) pool work without problems on this server. the load on the server is 10-15%

2018-08-31 15:10:12.972357 > Couldn't link returned work's job id with its handler. This should only happen if this process was recently restarted!
2018-08-31 15:10:12.976450 > Couldn't link returned work's job id with its handler. This should only happen if this process was recently restarted!
2018-08-31 15:10:12.982297 > Couldn't link returned work's job id with its handler. This should only happen if this process was recently restarted!
2018-08-31 15:10:12.985779 > Couldn't link returned work's job id with its handler. This should only happen if this process was recently restarted!
2018-08-31 15:10:12.996326 Worker XsEWtEBhWno1tuo6fYNxh4RQmPsdMMnE8V submitted share with hash > target:
2018-08-31 15:10:12.996403     Hash:   bde6f2c994fb6835e33e7b8635bcfd812275aadf5ad76511c08fdc5e196e02fb

**Comment by Rem559** [comment]
pool: rca-pool.ru:7799

**Comment by Rem559** [comment]
2018-08-31 16:13:30.713138 > Couldn't link returned work's job id with its handler. This should only happen if this process was recently restarted!
2018-08-31 16:13:38.498103 > Error while calling merged getauxblock on http://127.0.0.1:6888:
2018-08-31 16:13:38.498215 > Traceback (most recent call last):
2018-08-31 16:13:38.498274 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2018-08-31 16:13:38.498330 >     current.result = callback(current.result, *args, **kw)
2018-08-31 16:13:38.498388 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2018-08-31 16:13:38.498436 >     _inlineCallbacks(r, g, deferred)
2018-08-31 16:13:38.498557 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2018-08-31 16:13:38.498613 >     result = result.throwExceptionIntoGenerator(g)
2018-08-31 16:13:38.498671 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2018-08-31 16:13:38.498723 >     return g.throw(self.type, self.value, self.tb)
2018-08-31 16:13:38.498773 > --- <exception caught here> ---
2018-08-31 16:13:38.498820 >   File "/home/z/p2pool-dash/p2pool/util/deferral.py", line 41, in f
2018-08-31 16:13:38.498873 >     result = yield func(*args, **kwargs)
2018-08-31 16:13:38.498920 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2018-08-31 16:13:38.498971 >     result = result.throwExceptionIntoGenerator(g)
2018-08-31 16:13:38.499022 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2018-08-31 16:13:38.499079 >     return g.throw(self.type, self.value, self.tb)
2018-08-31 16:13:38.499133 >   File "/home/z/p2pool-dash/p2pool/util/jsonrpc.py", line 141, in _http_do
2018-08-31 16:13:38.499197 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2018-08-31 16:13:38.499261 > p2pool.util.jsonrpc.NarrowError: -12 Error: Keypool ran out, please call keypoolrefill first
2018-08-31 16:13:39.988940 > in handle_share_hashes:
2018-08-31 16:13:39.989056 > Traceback (most recent call last):
2018-08-31 16:13:39.989113 > Failure: twisted.internet.defer.TimeoutError: in GenericDeferrer

**Comment by Rem559** [comment]
when aux has bin disabled, this error ( Couldn't link returned work's job id with its handler.) does not go away

**Comment by Rem559** [comment]
reinstall dash_hash has helpd

**Comment by UdjinM6** [comment]
Thanks for reporting back with the solution! 👍
